name: vercel

on:
  push:
    branches:
      - main

  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🔨 Prepare Node environment
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: 🎉 Install project dependencies
        run: yarn

      - name: 🍱 Generate static files
        run: yarn run generate

      - name: 📦️ Copy Vercel config
        uses: canastro/copy-file-action@master
        with:
          source: "./vercel.json"
          target: "./dist/vercel.json"

      - name: 🍱 Deploy to Vercel
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          WORKING_DIRECTORY: "./dist"
